macronwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path

from . import views


app_name = 'website'
urlpatterns = [
    path('',views.home, name='home'),
    path('services/', views.service, name='services'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('careers/', views.careers, name='careers')
]

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


topic_choices = (
        ('enquiry', 'Enquiry'),
        ('sales', 'Sales'),
        ('support', 'Support'),
    )

class ContactForm(forms.Form):
    name = forms.CharField(max_length=255,required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=255,required=True)
    topic = forms.ChoiceField(choices=topic_choices,required=True)
    company = forms.CharField(max_length=255, required=False)  # Optional field  # Optional field
    message = forms.CharField(required=True,widget=forms.Textarea)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-contactForm'
        self.helper.form_class = 'form-control'
        self.helper.form_method = 'post'
        self.helper.form_action = 'website:contacts'

        self.helper.add_input(Submit('submit', 'Submit'))

website/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse


# Create your views here.
def home(request):
    return render(request,'home.html')

def service(request):
    return render(request, 'service.html')

def about(request):
    return render(request, 'about.html')

def contacts(request):
    if request.method == 'POST':
        print('In post')
        form = ContactForm(request.POST)
        if form.is_valid():
            print('form valid')
            subject = form.cleaned_data.get('topic')
            email_address = form.cleaned_data.get('email')
            client_name = form.cleaned_data.get('name')
            message = form.cleaned_data.get('message')
            company = form.cleaned_data.get('company')
            phone = form.cleaned_data.get('phone_number')
            full_message = f"""
            ________________________
            A message has been received from your website www.macronsynergy.co.zw.
            Here are the client details below 
            Client name: {client_name}
            Client company(if any): {company}, 
            contact number: {phone}
            email address: {email_address}
            ________________________
            Below is the message from the client
            ________________________


            {message}
            """
            try:
                print('sending email...')
                send_mail(subject=subject,
                          message = full_message,
                          from_email="enquiry@macronsynergy.co.zw",
                          recipient_list=["info@macronsynergy.co.zw"],
                          )
                messages.success(request, 'Thank you, we have received your message. We will get back to you soon. ')
                print('done')
            except BadHeaderError:
                return HttpResponse("Invalid header found")
            return redirect('website:contacts')
        else:
            cxt = {'form': form}
            return render(request, 'contacts.html', cxt)  # Redirect to a success page
    else:
        form = ContactForm()
    return render(request, 'contacts.html', {'form': form})

def careers(request):
    return render(request, 'careers.html')

website/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
<div class="container mt-5">
    <div class="shadow-lg p-3 mb-5 bg-primary-subtle rounded shadow-sizing">
        <div class="row">
            <div class="col-md-6 offset-md-3">
            <h1 class="display-6 text-center fw-bolder">Get to know us</h1>
            <hr class="text-center">

            <p class="ms-2 me-2 text-center fw-bold">We are a purpose driven organisation that is focused on digitalising businesses for sustainable growth, efficiency and optimization. We take pride in putting our clients' strategy in sync with our delivery and we do things right the first time always. Macron has a global portfolio that allows us to introduce latest technologies to the market and because we have a global portfolio we are well-versed with policies and statutory regulation in privacy and data protection. </p>

            <p class="ms-2 me-2 text-center fw-bold">Our unique mix of skills allows us to have a wide offering including consultancy, design, architecture, development, operations, training, and support. We are not a digital agency, yet we deliver all the services that one would—without the overheads.</p>

            <p class="fw-bold text-center text-dark" style="font-family: cursive; color:white">Team Macron</p>
            </div>
        </div>


    </div>
</div>


<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-6 text-white align-content-center">
            <h1 class="fw-bold display-6">Why Macron?</h1>
            <p>
                We enable our clients, as well as society, to move confidently into the digital future. We’re committed to building their long-term success, combining our global reach with local expertise and capabilities to serve our clients in over 10 countries.
            </p>

        </div>
        <div class="col-md-6 shadow-lg bg-white text-center">
            <img class="w-75" src="{% static 'img/Main.png' %}" alt="logo">
        </div>
    </div>

</div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-6 text-white">
            <h1 class="fw-bold display-6">Our Purpose</h1>
            <p>
                Empowering global progress through digital transformation. We want to create a world where technology drives economic growth and ensures decent work for all. By digitalizing businesses, we aim to enhance efficiency, accessibility, and sustainability, making a positive impact on communities worldwide.
            </p>
        </div>
    </div>

</div>

<div class="container">
    <h2 class="text-white fw-bold display-6">Our Values</h2>
    <div class="row g-4 d-flex align-items-center justify-content-center">
        <div class="col-md-4">
            <div class="shadow-lg p-3 mb-5 bg-primary-subtle rounded">
            <h3>Clients First</h3>
            <p>
            We continuously work to understand our clients' businesses and strive to resolve every concern to their satisfaction. We feel a responsibility to ensure their success. We let this obligation set the direction of our work and guide our actions.</p></div>
        </div>
        <div class="col-md-4">
            <div class="shadow-lg p-3 mb-5 bg-primary-subtle rounded">
            <h3>Speed</h3>
            <p> We never settle for the status quo. Instead, with speed and foresight, we anticipate challenges that lie ahead. We consider the future of IT, and of our clients' businesses, enhancing our ability to picture the future, and with our ecosystems, adapt to the changing business environment.</p> </div>
        </div>
        <div class="col-md-4">
            <div class="shadow-lg p-3 mb-5 bg-primary-subtle rounded">
            <h3>Teamwork</h3>
            <p>We believe that when a diverse group of individuals bring their unique world views together, share their wisdom and work toward a common goal, the results are extraordinary and far beyond what can be achieved by any one person.</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

website/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zimbabwe website, web development & Digital marketing - Macron Synergy</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.jpg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <meta name="facebook-domain-verification" content="c9qun3ysbljl9jn0xj7arb8kcsq95v" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'website:home' %}">
            <img src="{% static 'img/DarkBackLogo.png' %}" alt="Macron logo" width="130px" height="50px">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item px-4">
                <a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">
                    <span class="badge rounded-pill breadcr-bcgrnd">Home</span> </a>
              </li>
              <li class="nav-item px-4">
                <a class="nav-link" href="{% url 'website:services' %}">
                   <span class="badge rounded-pill breadcr-bcgrnd">Services</span>
                </a>
              </li>
              <li class="nav-item px-4">
                <a class="nav-link " href="{% url 'website:about' %}">
                    <span class="badge rounded-pill breadcr-bcgrnd" >About</span></a>
              </li>
              <li class="nav-item px-4">
                <a class="nav-link" href="{% url 'website:contacts' %}">
                   <span class="badge rounded-pill breadcr-bcgrnd">Contacts</span></a>
              </li>
              <li class="nav-item px-4">
                <a class="nav-link" href="{% url 'website:careers' %}">
                   <span class="badge rounded-pill breadcr-bcgrnd">Careers</span></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

{% if messages %}
<br>
<hr>
    <ul class="messages mt-5 bg-success">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }} text-white"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

    {% block content  %}
    {% endblock content  %}




    <footer class="text-bg-dark bg-black">
      <div class="container mt-2">
        <div class="row pt-2">
          <div class="col">
            <h6>Macron Synergy (pvt) limited</h6>
            <p class="small">741 Currie close, Waterfalls <br>Harare, Zimbabwe
            <br>Mon - Fri: 8am to 5pm
          </p>

          </div>
          <div class="col">
          </div>
          <div class="col">
            <h6>Contact Us</h6>
            <p class="small">Mobile number: +263 777 793 259 <br>
              Email: info@macronsynergy.co.zw
            </p>
          </div>
        </div>
      </div>
    <div class="container-fluid text-bg-dark py-2 bg-black">
      <hr>
      <div class="row">
        <div class="col-6">
          <small class="text-white-50">&copy; Copyright by Macron Synergy (pvt) limited</small>
        </div>
        <div class="col-2">
          <a href="https://www.facebook.com/profile.php?id=61559061581702"><i class=" text-white bi bi-facebook"></i></a>
          <a href="https://www.instagram.com/macronsynergy_zw/"><i class="text-white bi bi-instagram"></i></a>
          <a href="https://www.linkedin.com/company/macronsynergy/?viewAsMember=true"><i class="text-white bi bi-linkedin"></i></a>
        </div>
        <div class="col-4">
          <small class="text-white-50">Website Design & developed by <a href="https://www.macronsynergy.co.zw">Macron Synergy (pvt) limited</a></small>
        </div>
      </div>
    </div>
  </footer>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

website/templates/careers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <br>
    <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded mt-5">
        <h4 class="">Thank you for your interest in our organisation. Currently we don't have any open roles, but be on the lookout.</h4>
    </div>
</div>
{% endblock content %}

website/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy form example_form.helper %}

{% block content %}
<br>
<br>
<hr class="mt-5">

<div class="container mt-5">
    <div class="row mt-5">
        <div class="col-md-6">
            <h2 class="fw-bolder display-4 text-white mb-3">Let's solve your challenges</h2>
            <p style="color:lightgray">We are a purpose driven organisation that thrives to see businesses and communities succeeding through the usage of sustainable technology for good. </p>

            <p style="color:lightgray">Even if you don't have a full picture of your solution, we will help you to shape it into reality. Our deliveries are in sync with your own strategy. We always do the right thing, the first time. </p> <br>

            <div class="d-flex gap-4 align-items-center">
                <i class="bi bi-card-heading" style="color:lightgrey"></i>

                <p style="color:lightgrey">Macron Synergy (private) Limited
                    <br>
                    <span class="small" style="color:lightgray">
                    <small>Company number: 14289/2018 <br>
                        Registered in Zimbabwe and South Africa</small>  </span>  
                </p>

            </div>

            <div class="d-flex gap-4 align-items-center">
                <i class="bi bi-building" style="color:lightgrey"></i>
                <p style="color:lightgrey">
                    741 Currie Close, Parktown, Waterfalls <br>
                    Harare, Zimbabwe
                </p>
            </div>


            <div class="d-flex gap-4">
                <i class="bi bi-envelope" style="color:lightgrey"></i>
                <p style="color:lightgrey">
                    info@macronsynergy.co.zw
                </p>
            </div>

            <div class="d-flex gap-4">
                <i class="bi bi-phone" style="color:lightgrey"></i>
                <p style="color:lightgrey">
                    +263777 793 259
                </p>
            </div>


        </div>
        <div class="col-md-6">
            {% csrf_token %}
            {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

website/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Carousel start -->
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" >
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
    </div>

    <div class="carousel-inner carousel-img-size">
      <div class="carousel-item active">
        <img src="{% static 'img/womencoding.jpg' %}" style="filter: brightness(0.7);" class="d-block w-100" alt="img">
        <div class="carousel-caption text-start mb-5">
                <h1 class="text-light main-text display-2 fw-bolder text-capitalize">Online Presences Solutions</h1>
                <p class="">Get your brand to standout & have credibility from your customers. We have it all to ensure your brand is well known, from static websites to dynamic websites and web applications. Professional emails for SME & large Enterprises. Mobile applications for iOS devices and android devices. We provide digital and social media marketing as well. </p>
                <a href="{% url 'website:services' %}" class="btn macronbutton mt-3">Learn More</a>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/emile.jpg' %}" class="d-block w-100" style="filter: brightness(0.7);" alt="img">
        <div class="carousel-caption text-start mb-5 d-none d-md-block">
          <h1 class="text-light main-text display-2 fw-bolder text-capitalize">Website Development</h1>
            <p>Our websites are fully responsive on desktop & mobile. We make both static websites and dynamic websites. We take care of Integrations to payment systems and live chatting systems. If you don't have a design, don't worry we have got you. We take pride in our attention to detail to give your clients a great user experience. </p>
            <a href="{% url 'website:services' %}" class="btn macronbutton mt-3">Learn More</a>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/email.jpg' %}" class="img-fluid d-block w-100" alt="img">
        <div class="carousel-caption text-start mb-5 d-none d-md-block">
          <h1 class="text-light main-text display-2 fw-bolder text-capitalize">Microsoft 365 Governance, PowerApps & Power Automate</h1>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/choong.jpg' %}" class="img-fluid d-block w-100" style="filter: brightness(0.7);" alt="img">
        <div class="carousel-caption text-start mb-5 d-none d-md-block">
          <h1 class="text-light main-text display-2 fw-bolder text-capitalize">Insider Risk management, Data Analytics and Visualisation</h1>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/code.jpg' %}" class="d-block w-100" alt="img">
        <div class="carousel-caption text-start mb-5 d-none d-md-block">
          <h1 class="text-light main-text display-3 fw-bolder text-capitalize">Software Development technical Debt & Documentation</h1>
            <p>We have experienced Senior Engineers that can take care of your technical documentation to allow you to focus on the more pressing issues. We can handle all your technical debt for you.</p>
            <a href="{% url 'website:services' %}" class="btn macronbutton mt-3">Learn More</a>
        </div>
      </div>
      

    </div>
  </div>
<!-- Carousel end -->





<!-- Header start -->
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-light main-text fw-bolder text-capitalize text-center mt-5">
                We are a progressive digital growth accelerator.
            </h1>
            <hr class="col-2 offset-5 mb-5" style="color: #eb8228;">
        </div>
    </div>
</div>
<!-- Header end -->





<!-- Card stacking start -->
<div class="container" id="stacking">
    <div class="row">
        <div class="col-12 clstack justify-content-evenly"> <img class="clstackimg" src="{% static 'img/codioful.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Digital Software Systems</h2>
                <br>
                <ul>
                    <li> Custom POS systems</li>
                    <li> Inventory systems</li>
                    <li> Litigation management systems</li>
                    <li> Medical management systems</li>
                    <li>School management & reporting systems</li>
                </ul>
                <br>
                <a href="{% url 'website:contacts' %}" class="btn macronbutton">Get quote</a>
            </div> 
        </div>
        <div class="col-12 clstack"> <img class="clstackimg" src="{% static 'img/3dsplash.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Website design & development & Mobile applications</h2>
                <br><h4>Empower Your Business with a Stunning Website</h4><br>
                <p class="stacking-text">Take your online presence to the next level with a professionally crafted website tailored to your unique brand and goals. Our team of experts specializes in designing and developing visually appealing and user-friendly websites that captivate audiences and drive results.</p>
                <a href="{% url 'website:contacts' %}" class="btn macronbutton">Get quote</a>
            </div>
        </div>
        <div class="col-12 clstack"> <img class="clstackimg" src="{% static 'img/richard.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Data Analysis & Visualization</h2>

                <br><h4>Uncover Insights, Transform Data</h4>
                <br>
                <p class="stacking-text">Harness the power of data to make informed decisions and drive growth with our data analysis and visualization services. </p>
                <br>
                <a href="{% url 'website:contacts' %}" class="btn macronbutton">Get quote</a>
            </div>  
        </div>
        <div class="col-12 clstack"> <img class="clstackimg" src="{% static 'img/milad.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Microsoft M365, PowerApps & PowerAutomate</h2>
                <br>
                <ul>
                    <li> Develop PowerApps Enterprise applications</li>
                    <li> Develop Power Automate workflows for process automation</li>
                    <li> M365 Governance</li>
                    <li>M365 Administration</li>
                    <li>Insider Risk Management</li>
                </ul>
                <br>
                <a href="{% url 'website:contacts' %}" class="btn macronbutton">Get quote</a>
            </div> 
        </div>
        <div class="col-12 clstack"> <img class="clstackimg" src="{% static 'img/pawel.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Process Automation</h2>
                <br>
                <ul>
                    <li> Data capturing automation</li>
                    <li> Downtime systems capturing</li>
                    <li> Robotic Process Automation e.g. Trading robots</li>
                </ul>
                <br>
                <a href="{% url 'website:contacts' %}" class="btn macronbutton">Get quote</a>
            </div> 
        </div>
        <div class="col-12 clstack"> <img class="clstackimg" src="{% static 'img/codiofulunsplash.jpg' %}" alt="bg image">
            <div class="stacking-container">
                <h2 class="gradient-text">Business Emails</h2>
                <br><h4>Unlock the Potential of Your Brand with a Custom Email Address</h4><br>
                <p class="stacking-text">Elevate your business's professionalism and credibility by securing a custom email address tailored to your brand.</p>
                <a href="#" class="btn macronbutton">Get quote</a>
            </div>
        </div>
    </div>
</div>
<!-- Card stacking end -->




<!-- Code for cards start -->
<div class="container ">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-light main-text fw-bolder text-capitalize text-center mt-5">
                Why Should You Choose Us?
            </h1>
            <hr class="col-2 offset-5 mb-5" style="color: #eb8228;">
        </div>
    </div>
</div>


  <div class="container mt-5">
    <div class="row row-cols-md-3" style="padding-left: 4em;">
      <div class="col mb-2">
        <div class="card h-100 card-item" style="width: 17rem;">
          <div class="card-icon"><i class="bi bi-person-check"></i></div>
  
          <div class="card-body">
            <h5 class="card-title text-center fw-bolder text-uppercase">Our Expertise</h5>
            <p class="card-text">We have done business in 3 continents across 10 countries. Our staff are highly experienced and they have been transforming the digital world across boarders.
                We have worked with different enterprises in different industries from Tech, health, construction, architecture, clothing and education. </p>
          </div>
        </div>
      </div>
      <div class="col mb-2">
        <div class="card h-100 card-item" style="width: 17rem;">
          <div class="card-icon"><i class="bi bi-shield-check"></i></div>
          <div class="card-body">
            <h5 class="card-title text-center text-uppercase fw-bolder">Security</h5>
            <p class="card-text">
              We are aware that some of our clients have minimal knowledge on cyber security so this is a service that we will offer when you engage us 
            . We follow the Zero trust approach to ensure that all the systems and services we provide are of high cyber security standards. We are committed to protecting your data.</p>
          </div>
        </div>
      </div>
      <div class="col mb-2">
        <div class="card h-100 card-item" style="width: 17rem;">
          <div class="card-icon"><i class="bi bi-cpu"></i></div>
          <div class="card-body">
            <h5 class="card-title text-center text-uppercase fw-bolder">Innovation & Tech</h5>
            <p class="card-text"> Innovation is our middle name. We thrive to transform your business through using the latest trending technologies. We ensure that your customers get the best user experience on all 
                of our products and services.
            </p>
          </div>
        </div>
      </div>
    </div>
    </div>
  <!-- Code for cards end -->



   <!-- Our Strategic Partners start -->
  <div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-light main-text fw-bolder text-capitalize text-center mt-5">
                Our Strategic Partners
            </h1>
            <hr class="col-2 offset-5 mb-5">
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-3 text-center">
            <img class="img-fluid" src="{% static 'img/aws.png' %}" style="height: 100px; width: auto;" alt="aws logo">
        </div>
        <div class="col-md-3 text-center">
            <img class="img-fluid" src="{% static 'img/microsoft.png' %}" style="height: 120px; width: auto;" alt="ms logo">
        </div>
        <div class="col-md-3 text-center">
            <img class="img-fluid" src="{% static 'img/webdev.png' %}" style="height: 80px; width: auto;" alt="web logo">
        </div>
        <div class="col-md-3 text-center">
            <img class="img-fluid" src="{% static 'img/bootstrap.png' %}" style="height: 100px; width: auto;" alt="partner logo">
        </div>
    </div>
</div>
   <!-- Our Strategic Partners end -->





 <!-- Sustainable development start -->
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-light main-text fw-bolder text-capitalize text-center mt-5">
                Sustainable Development Goals
            </h1>
            <hr class="col-2 offset-5 mb-5" style="color: #eb8228;">
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-12 text-center">
            <br>
            <h2 class="sustainable-text">We're a purpose driven organisation.</h2><br>
            <h4 class="text-light">Our organisation is taking action in issues 
                that are affecting the world.
            </h4>
            <br>
            <a href="{% url 'website:contacts' %}" class="btn macronbutton">Partner with us</a>
        </div>
        <div class="col-md-2 col-sm-12 text-center mb-2">
            <img class="img-fluid" src="{% static 'img/sdg5.png' %}" alt="img">
        </div>
        <div class="col-md-2 col-sm-12 text-center mb-2">
            <img class="img-fluid" src="{% static 'img/sdg8.png' %}" alt="img">
        </div>
        <div class="col-md-2 col-sm-12 text-center mb-2">
            <img class="img-fluid" src="{% static 'img/sdg9.png' %}" alt="img">
        </div>
    </div>
</div>
 <!-- Sustainable development end -->


{% endblock %}